/** 文本配置 */
export const TextConfig = {
    Prop_Path: "common/{0}/spriteFrame",
    Building_Path1: "map/land/{0}/spriteFrame",
    Building_Path2: "map/building/{0}/spriteFrame",
    Building_SpPath: "spine/building/{0}",
    Mood_Path: "map/pet/{0}/spriteFrame",

    Land_Key: "{0}_{1}",
    Pet_Mood_Prop: "+{0}",
    Prop_Show: "x{0}",
    Produce_Lock1: "城堡等级达到{0}级",
    Produce_Lock2: "建筑物等级达到{0}级",
    Level_Text: "{0}级",
    Level_Text2: "/{0}",
    Ver_Text: "ver:{0}.{1}.{2}.{3}",
    Queue_Text: "{0}/{1}",

    Function_Tip: "开发中，敬请期待",
    Function_Tip2: "暂时没有该功能",

    Update_New: "发现新版本，需要更新",
    Update_Error: "更新失败，请检测网络后再重试",
    Update_Success: "更新成功，是否立即重启游戏",

    Building_Sure_Tip: "这个位置有其他建筑哦~",
    Building_Cell_Tip: "此建筑不能售卖!",
    // Building_Edit_Error: "该建筑不能编辑!",
    Building_New_Error: "该位置建筑不能放置!",
    Building_Product_Full: "当前生产队列已满，请稍后再加入制作",
    Building_Product_Start: "开始制作",
    Building_Product_Delete: "是否删除此生产",
    Building_Product_Get_Error: "还未生产完成，请稍后再来领取",
    Building_Product_Error: "建筑正在升级中，等升级完成后再制作吧～",
    Building_Upgrade_Error: "建筑正在制作中，等制作完成后再升级吧～",
    Building_Upgrade_Start: "开始升级建筑",
    Building_Flipx_Failed: "翻转失败",
    Building_Recycle_Error1: "这个建筑正在制作中，请稍后完成后，再回收吧～",
    Building_Recycle_Error2: "这个建筑正在升级中，请稍后完成后，再回收吧～",
    Castle_Condition1: "通过水下管道城{0}-{1}",
    Castle_Condition2: "精灵等级达到{0}级",
    Castle_Condition3: "人物等级达到{0}",
    Upgrade_Condition_Error: "你的{0}不足，暂时还不能升级哦～",
    Building_Shop_Buy_Success: "购买建筑成功",
    Building_Product_Success: "恭喜你，制作已完成～",
    Building_Upgrade_Success: "恭喜你，{0}升级已完成～",
    Building_Built_Success: "恭喜你，{0}建造已完成～",
    Cloud_Unlock_Success: "恭喜你，扩张已完成～",
    Speed_Words_Tip1: "是否想要通过背单词加速？\n（每次建造可用1次单词加速，每次背10个单词，每个单词加速20秒）",
    Speed_Words_Tip2: "是否想要通过背单词加速？\n（每次升级可用1次单词加速，每次背10个单词，每个单词加速20秒）",
    Speed_Words_Tip3: "是否想要通过背单词加速？\n（每次制作可用1次单词加速，每次背10个单词，每个单词加速20秒）",
    Speed_Words_Tip4: "是否想要通过背单词加速？\n（每次扩张可用1次单词加速，每次背10个单词，每个单词加速20秒）",
    Building_Success_Type1: "建造成功",
    Building_Success_Type2: "升级成功",

    Role_Text1: "点我做啥",
    Role_Text2: "不能移动的位置",

    Cloud_Unlock_Tip: "是否解锁乌云",
    Cloud_Unlock_Error1: "需要先拓张外围区域，才能拓张这里",

    Net_Error: "网络异常，请检查后再试",

    Account_Logout_Tip: "账号已在其他地方登录，如不是本人操作，请修改密码后重新登录",
    Agree_Maksure_Tip: "请先同意用户协议与隐私协议",
    Account_Null_Tip: "账号不能为空",
    Password_Null_Tip: "密码不能为空",
    Phone_Null_Tip: "手机号不能为空",
    Code_Null_Tip: "验证码不能为空",
    Get_Code: "获取验证码",
    Get_Code_Time: "({0}s)",
    Get_Code_Success: "获取验证码成功",
    ActivationCode_Null_Tip: "激活码不能为空",

    US: "美",
    EN: "英",

    Word_Learn_Count: "共计{0}词",
    Level_Index: "第{0}关",

    //成就相关
    Achieve_OverView: "成就总览",
    Achieve_GrowUp: "人物成长",
    Achieve_Social: "社交",
    Achieve_Dungeon: "副本",
    Achieve_SpriteTrain: "精灵培养",
    Achieve_AbilityTrain: "能力培养",
    Achieve_GoTo: "前往",
    Achieve_GetAward: "领取",
    Achieve_Error_Medal_ExceedLimit: "最多只能展示{0}枚勋章!",

    //单词查找相关
    Search_Word_Fail: "未查找到该单词详情",

    //帮助菜单相关
    Help_ImageDisplay: "图示",

    //好友系统相关
    Friend_List: "好友列表",
    Friend_Add: "添加好友",
    Friend_Apply: "好友申请",
    Friend_Notify: "好友通知",
    Friend_InputEmptyTip: "好友ID不能为空",
    Friend_NoFindUser: "没找到此用户",
    Friend_CannotAddSelfTip: "不能添加自己",
    Friend_AddSuccess: "添加好友成功",
    Friend_AcceptApply: "已同意好友添加申请",
    Friend_RefuseApply: "已拒绝好友添加申请",
    Friend_EmailSys: "系统消息",
    Friend_RecvAwardSucc: "获得邮件奖励",
    Friend_DelFriendSucc: "删除好友成功",

    All_level_Tip: "恭喜完成所有关卡",

    //商店相关
    Shop_Figure: "形象商店",
    Shop_Fragment: "碎片区",
    Shop_Building: "建筑商店",
    Shop_Decoration: "装饰类",
    Reading_Success_Tip: "朗读单词正确",
    Reading_Error_Tip: "朗读单词错误",

    ReviewPlan_Study: "已学单词:{0}",
    ReviewPlan_Review: "已复习单词:{0}",
    ReviewPlan_Null: "今日没有需要复习的单词",
    ReviewPlan_End: "完成本组复习,当前还剩余{0}词未复习\n继续加油吧~",
    ReviewPlan_End2: "恭喜完成今日所有教材单词的复习规划\n继续加油吧~",
    ReviewPlan_End3: "恭喜完成今日所有单词大冒险的复习规划\n继续加油吧~",

    PetInteraction_Tip: "互动次数不足",
    PetUpgrade_Tip: "升级成功",

    Sure_Tip: "确定",
    Cancel_Tip: "取消",
    Textbook_Delete_Tip: "确定要删除s%吗？请注意删除后学习进度数据依然会保存",
    Textbook_Change_Tip: "是否切换s%注意切换后复习有奖里面的教材单词复习也会同步为新词书",
    Success_Change_Book: "成功切换当前学习词书s%",
    Begin_Break_Through_Tip: "是否延续上一次闯关进度",
    Continue_From_Last_Time_Tip: "延续上次",
    Restart_Tip: "重新开始",
}